version: '3.8'

services:
  db:
    image: postgres:15
    container_name: licenta_db
    environment:
      POSTGRES_DB: portfolio_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: licenta_redis
    ports:
      - "6379:6379"

volumes:
  pgdata: